services:
  - type: web
    name: puppeteer-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"
